### ISSUE TITLE
Predloge HTML

### ISSUE THREAD

**Issue by jaanos** [nocmatic/prevozi#3]
Datoteke HTML dajta v mapo `views`, saj bottlov ukaz `template` privzeto gleda v to mapo, poleg tega pa bo struktura projekta nekoliko bolj pregledna.

**Comment by PavesicL** [comment]
sem popravil, ali je treba kje nastavit mapo, kjer so shranjene template datoteke? In zakaj je delovalo, čeprav so bile datoteke kar tako in ne v views?

**Comment by jaanos** [comment]
V `bottle.py` je definirana spremenljivka `TEMPLATE_PATH` - to je seznam map, kjer bottle gleda za predloge. Privzeto vsebuje trenutni imenik in imenik `views`.
