### ISSUE TITLE
Razlika med return redirect() in return template()

### ISSUE THREAD

**Issue by PavesicL** [nocmatic/prevozi#5]
S strani login želim, da se ob uspešnem prijavljanju uporabnika preusmeri na stran z naslovom /<uporabnisko_ime>. Kako se to naredi oz katera od metod (z redirect ali s template) je "pravilnejša"?

**Comment by jaanos** [comment]
Vedno, ko uporabljata metodo `POST`, naredita `redirect`, npr.
```python
redirect('/uporabnik/{0}'.format(uporabnisko_ime))
```
Kot vidita, je bolje, če imata za spremenljive parametre določeno predpono v poti, da ne pride do konflikta z ostalimi, že definiranimi potmi.

Pri metodi `GET` lahko seveda tudi uporabita `redirect`, npr. če je prišlo do kakšne napake in bi rada uporabnika preusmerila drugam. `template` seveda uporabita takrat, ko je uporabnik na pravi strani in bi jo rada prikazala.
